[project]
authors = [
    { name = "Zebedee Nicholls", email = "zebedee.nicholls@climate-resource.com"},
]
requires-python = ">=3.12"
dependencies = [
    "cmip7-data-request-api>=1.2.2",
    # "esgvoc>=1.1.2",
    "esgvoc",
    "pint>=0.25",
    "pre-commit>=3.3.1",
    "pytest>=8.4.2",
    "pytest-regressions>=2.8.3",
]
name = "data_specs_version"
version = "0.1.0"
description = "Prototype to see what it would be like to define a data specs version for CMIP7 based on the state of multiple repositories"
readme = "README.md"

[tool.uv]
package = false

[[tool.uv.sources.esgvoc]]
git = "https://github.com/znichollscr/esgf-vocab.git"
rev = "86412e104d61cb2acce346be839d755c5a806443"

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "D",
    "PL",
    "TRY",
    "NPY",
    "RUF",
    "UP",
    "S",
]
unfixable = [ ]
ignore = [
    "D200",
    "D400",
    "UP007",
]

[tool.ruff.lint.per-file-ignores]
"test*.py" = [
    "D",
    "S101",
    "PLR2004",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
